url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title:   MadebyGraham
email:   mattgraham@madebygraham.com
twitter_username: mattgraham
github_username:  mattgraham
repository:   mattgraham/mattgraham.github.io
timezone: 'America/Detroit'

assets:
    sources:
        - assets/styles
        - assets/images
        - assets/js

plugins:
  - jekyll-postcss-v2
  - jekyll-get-json

highlighter:  rouge
markdown:    kramdown

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js

jekyll_get_json:
  - data: team
    json: 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/130'
  - data: michigan_football
    json: 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/michigan/schedule'
  - data: ncaa_football
    json: 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard'