url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title:   MadebyGraham
email:   mattgraham@madebygraham.com
twitter_username: mattgraham
github_username:  mattgraham
repository:   mattgraham/mattgraham.github.io

assets:
    sources:
        - assets/styles
        - assets/images
        - assets/js

plugins:
  - jekyll-postcss-v2

highlighter:  rouge
markdown:    kramdown

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js